/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalholab3final.telas;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;

/**
 *
 * @author Pedro
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        btnDashboard.setVerticalTextPosition(SwingConstants.TOP);
        btnDashboard.setHorizontalTextPosition(SwingConstants.CENTER);
        btnProjeto.setVerticalTextPosition(SwingConstants.TOP);
        btnProjeto.setHorizontalTextPosition(SwingConstants.CENTER);
        btnPessoa.setVerticalTextPosition(SwingConstants.TOP);
        btnPessoa.setHorizontalTextPosition(SwingConstants.CENTER);
        btnTarefa.setVerticalTextPosition(SwingConstants.TOP);
        btnTarefa.setHorizontalTextPosition(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bemVindoLbl = new javax.swing.JLabel();
        orientacaoLbl = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnTarefa = new javax.swing.JButton();
        btnProjeto = new javax.swing.JButton();
        btnPessoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(296, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(296, 550));

        bemVindoLbl.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        bemVindoLbl.setForeground(new java.awt.Color(255, 255, 255));
        bemVindoLbl.setText("Bem-Vindo ao TasKiller");

        orientacaoLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orientacaoLbl.setForeground(new java.awt.Color(255, 255, 255));
        orientacaoLbl.setText("O que deseja fazer:");

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setForeground(new java.awt.Color(0, 102, 255));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalholab3final/icones/dashboard.png"))); // NOI18N
        btnDashboard.setText(" Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnTarefa.setBackground(new java.awt.Color(255, 255, 255));
        btnTarefa.setForeground(new java.awt.Color(0, 102, 255));
        btnTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalholab3final/icones/icon.png"))); // NOI18N
        btnTarefa.setText(" Tarefas");
        btnTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarefaActionPerformed(evt);
            }
        });

        btnProjeto.setBackground(new java.awt.Color(255, 255, 255));
        btnProjeto.setForeground(new java.awt.Color(0, 102, 255));
        btnProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalholab3final/icones/idea.png"))); // NOI18N
        btnProjeto.setText("Projetos");
        btnProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjetoActionPerformed(evt);
            }
        });

        btnPessoa.setBackground(new java.awt.Color(255, 255, 255));
        btnPessoa.setForeground(new java.awt.Color(0, 102, 255));
        btnPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalholab3final/icones/multiple-users-silhouette.png"))); // NOI18N
        btnPessoa.setText(" Pessoas");
        btnPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemVindoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orientacaoLbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTarefa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPessoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bemVindoLbl)
                .addGap(18, 18, 18)
                .addComponent(orientacaoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnProjeto)
                .addGap(18, 18, 18)
                .addComponent(btnTarefa)
                .addGap(18, 18, 18)
                .addComponent(btnPessoa)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        try {
            DashBoard d = new DashBoard();
            d.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Mensagem.erroAcesso("Erro ao acessar Dashboard");
        } catch (ClassNotFoundException ex) {
            Mensagem.erroAcesso("Erro ao acessar Dashboard");
        }
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjetoActionPerformed
        try {
            ListarProjetos p = new ListarProjetos();
            p.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Mensagem.erroAcesso("Erro ao acessar Projetos");
        } catch (ClassNotFoundException ex) {
            Mensagem.erroAcesso("Erro ao acessar Projetos");
        }
    }//GEN-LAST:event_btnProjetoActionPerformed

    private void btnTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarefaActionPerformed
        ListarTarefas t = new ListarTarefas();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTarefaActionPerformed

    private void btnPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaActionPerformed
        try {
            ListarPessoas lp = new ListarPessoas();
            lp.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Mensagem.erroAcesso("Erro ao acessar Pessoas");
        } catch (ClassNotFoundException ex) {
            Mensagem.erroAcesso("Erro ao acessar Pessoas");
        }
    }//GEN-LAST:event_btnPessoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bemVindoLbl;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnPessoa;
    private javax.swing.JButton btnProjeto;
    private javax.swing.JButton btnTarefa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orientacaoLbl;
    // End of variables declaration//GEN-END:variables
}
